config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dogs, only: [:create, :update, :show, :index, :new ]
  resources :shelters, only: [:show, :index]
  resources :owners, only: [:show, :index]

  get '/dogs/:id/adopt', to: 'dogs#adopt'
  get '/dogs/:id/abandon', to: 'dogs#abandon'
  get '/', to: 'application#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner, optional: true
  belongs_to :shelter, optional: true
  accepts_nested_attributes_for :owner, :reject_if => :all_blank
  validates :name, presence: true
  validates :age, presence: true
  validates :breed, presence: true

  def self.owned
    where(shelter_id: nil)
  end

  def self.adoptable
    where(owner_id: nil)
  end

end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs
  has_many :shelters, through: :dogs
  validates :name, presence: true

  def self.dog_owners
    all.reject{|owner| owner.dogs.length == 0}
  end
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :dogs
  has_many :owners, through: :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper

  def welcome
    render :'layouts/welcome'
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # layout false

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to dog_path(@dog)
    else
      redirect_to new_dog_path
    end
  end

  def show
    @dog = Dog.find(params[:id])
    # render layout:false
  end

  def adopt
    @dog = Dog.find(params[:id])
  end

  def abandon
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    if @dog.save
      redirect_to dog_path(@dog)
    else
      redirect_to "/dogs/#{@dog.id}/adopt"
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :shelter_id, :owner_id, owner_attributes: [:name])
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def show
    @owner = Owner.find(params[:id])
  end

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  layout 'sad_puppy'
  
  def show
    @shelter = Shelter.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

    def display_gender(dog)
        if dog.sex == 'M'
            "male"
        else
            "female"
        end
    end

end

app/views/dogs/_owned_dogs.html.erb
<table>
      <tr>
        <th>Name</th>
        <th>Breed</th>
        <th>Age</th>
        <th>Sex</th>
        <th>Owner</th>
        <th>Abandon</th>
      </tr>
    <% dogs.each do |dog|%>
        <%# if dog.owner %>
        <tr>
            <td><strong><%=link_to dog.name, dog_path(dog)%></strong></td>
            <td><%=dog.breed%></td>
            <td><%= dog.age%></td>
            <td><%= display_gender(dog) %></td>
            <td><%= dog.owner.name%></td>
            <td><button><%= link_to "Abandon", "/dogs/#{dog.id}/abandon" %> </button> </td>
        </tr>
        <%# end %>
    <% end %>
</table>

app/views/dogs/_shelter_dogs.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Breed</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Shelter</th>
    <th>Adopt</th>
  </tr>
<% dogs.each do |dog|%>
  <%# if !dog.owner %>
  <tr>
    <td><strong><%=link_to dog.name, dog_path(dog)%></strong></td>
    <td><%=dog.breed%></td>
    <td><%= dog.age%></td>
    <td><%= display_gender(dog) %></td>
    <td><%= link_to dog.shelter.name, shelter_path(dog.shelter) %></td>
    <td><button><a href="/dogs/<%=dog.id%>/adopt">Adopt Me!</a></button> </td>
  </tr>
  <%# end %>
<% end %>
</table>

app/views/dogs/_stats.html.erb
<div>
    <p># of Puppies: <%= dogs.count{|dog| dog.age <= 1}%></p>
    <p># of Mutts: <%= dogs.count{|dog| dog.breed.downcase == 'mutt'}%></p>
    <p># of Males: <%= dogs.count{|dog| dog.sex == 'M'}%></p>
    <p># of Females: <%= dogs.count{|dog| dog.sex == 'F'}%></p>
</div>

app/views/dogs/abandon.html.erb
<%= form_for @dog do |f| %>
  <label>Dog's Name:</label>
  <%= f.text_field :name %>

  <br>
  </br>

  <label><strong>Select an Shelter:</strong></label>
  <%= f.collection_radio_buttons :shelter_id, Shelter.all, :id, :name  %>

  <br>
  </br>

  <%= f.hidden_field :owner_id, :value => nil %>

  <br>
  </br>
  <%= f.submit "Abandon!" %>
<% end %>

app/views/dogs/adopt.html.erb
<%= form_for @dog do |f| %>
  <label>Dog's Name:</label>
  <%= f.text_field :name %>

  <br>
  </br>

  <label><strong>Select an owner:</strong></label>
  <%= f.collection_radio_buttons :owner_id, Owner.all, :id, :name  %>

  <br>
  </br>


  <label><strong>Or enter a new owner's name: </strong></label>

  <%= f.fields_for :owner_attributes do |o| %>
    <%= o.text_field :name %>
  <% end %>
  <%= f.hidden_field :shelter_id, :value => nil %>

  <br>
  </br>
  <%= f.submit "Adopt!" %>
<% end %>

app/views/dogs/index.html.erb
<h1>Dogs up for Adoption:</h1>
<%= render partial: 'shelter_dogs', locals: {dogs: Dog.adoptable} %>


<h1>Adopted Dogs:</h1>
<%= render partial: 'owned_dogs', locals: {dogs: Dog.owned} %>

app/views/dogs/new.html.erb
<h1>Create a New Dog</h1>
<%= form_for @dog do |f| %>
  <label>Dog's Name:</label>
  <%= f.text_field :name %>

  <br>
  </br>

  <label>Dog's Age:</label>
  <%= f.number_field :age %>

  <br>
  </br>

  <label>Dog's Breed:</label>
  <%= f.text_field :breed %>

  <br>
  </br>

  <label><strong>Select an owner:</strong></label>
  <%= f.collection_radio_buttons :owner_id, Owner.all, :id, :name  %>

  <br>
  </br>


  <label><strong>Or enter a new owner's name: </strong></label>

  <%= f.fields_for :owner_attributes do |o| %>
    <%= o.text_field :name %>
  <% end %>

  <br>
  </br>
  <%= f.submit "Create!" %>
<% end %>

app/views/dogs/show.html.erb
 <h1><strong><%= @dog.name%></strong></h1>
    <ul>
      <li>Breed: <%= @dog.breed%> </li>
      <li>Age: <%= @dog.age%></li>
      <% if @dog.sex == 'M' %>
        <li>Sex: male</li>
      <% else %>
        <li>Sex: female</li>
      <% end %>
      <% if @dog.shelter %>
        <li>Shelter: <%= link_to @dog.shelter.name, shelter_path(@dog.shelter) %></li>
        <li> <%= link_to "Adopt!", "/dogs/#{@dog.id}/adopt" %></li>
      <% elsif @dog.owner %>
        <li>Owner: <%= link_to @dog.owner.name, owner_path(@dog.owner) %></li>
        <li> <%= link_to "Abandon!", "/dogs/#{@dog.id}/abandon" %></li>
      <% end %>
      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FixMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/sad_puppy.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FixMe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
   <img src="/images/dogs-2195708_640.jpg" alt="a sad puppy dog">
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<h1>Welcome to Adopt-A-Pet!</h1>

<h3><%=link_to 'Find a Shelter', shelters_path %> </h3>

app/views/owners/index.html.erb
<h1>All Owners:</h1>

<% Owner.dog_owners.each do |owner| %>
  <h2><%= owner.name %>'s dogs:</h2>
    <%= render partial: 'dogs/owned_dogs', locals: {dogs: owner.dogs} %>
    <%= render partial: 'dogs/stats', locals: {dogs: owner.dogs} %>
  <% end %>

app/views/owners/show.html.erb
<h1><%= @owner.name %></h1>

<h3>Dogs:</h3>

  <%= render partial: 'dogs/owned_dogs', locals: {dogs: @owner.dogs} %>
  <%= render partial: 'dogs/stats', locals: {dogs: @owner.dogs} %>
  

app/views/shelters/index.html.erb
<h1>All Shelters</h1>

<% Shelter.all.each do |shelter| %>
  <h3><%= link_to shelter.name, shelter_path(shelter) %></h3>

<%= render partial: 'dogs/shelter_dogs', locals: {dogs: shelter.dogs} %>
<%= render partial: 'dogs/stats', locals: {dogs: shelter.dogs} %>
<% end %>

app/views/shelters/show.html.erb
<h1><%= @shelter.name %></h1>

<%= render partial: 'dogs/shelter_dogs', locals: {dogs: @shelter.dogs} %>
<%= render partial: 'dogs/stats', locals: {dogs: @shelter.dogs} %>